GRANT REPLICATION SLAVE, REPLICATION CLIENT, SELECT ON *.* TO 'replicator'@'%';
FLUSH PRIVILEGES;

USE bugzilla;
CREATE TABLE bugs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	summary VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	send_to_kanban BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
